stages: 
  - build
  - style
  - tests
  - deploy
build:
  stage: build
  script:
    - cd ./cat/
    - make
    - cd ../grep/
    - make
  after_script:
     - chmod a+x notifyer.sh
     - ./notifyer.sh CI "$CI_JOB_STATUS" "$CI_COMMIT_AUTHOR" "$CI_COMMIT_BRANCH" "$CI_COMMIT_MESSAGE" "$CI_PIPELINE_ID" "$CI_JOB_STAGE" 
  artifacts:
    paths:
      - ./cat/s21_cat
      - ./grep/s21_grep
    expire_in: 30 days
  tags: 
    - ajhin2 
  allow_failure: false   
style:
  stage: style
  script:
    - cd ./cat/
    - make linter
    - cd ../grep/
    - make linter   
  after_script:
    - chmod a+x notifyer.sh
    - ./notifyer.sh CI "$CI_JOB_STATUS" "$CI_COMMIT_AUTHOR" "$CI_COMMIT_BRANCH" "$CI_COMMIT_MESSAGE" "$CI_PIPELINE_ID" "$CI_JOB_STAGE"
  needs: 
    - job: build
  tags:
    - ajhin2
  allow_failure: false 
tests:
  stage: tests
  needs: 
    - job: build
      artifacts: true
    - job: style
  script:
    - chmod +x ./cat/tests/s21_cat_lin_test1.sh 
    - ./cat/tests/s21_cat_lin_test1.sh 
    - chmod +x ./grep/tests/s21_grep_lin_test1.sh 
    - ./grep/tests/s21_grep_lin_test1.sh 
  after_script:
    - chmod a+x notifyer.sh
    - ./notifyer.sh CI "$CI_JOB_STATUS" "$CI_COMMIT_AUTHOR" "$CI_COMMIT_BRANCH" "$CI_COMMIT_MESSAGE" "$CI_PIPELINE_ID" "$CI_JOB_STAGE"
  tags:
    - ajhin2
  allow_failure: false    
deploy:
  stage: deploy
  needs: 
    - job: build
      artifacts: true
    - job: style
    - job: tests
  script:
    - chmod a+x deployer.sh
    - ./deployer.sh 10.54.202.246 student
  after_script:
    - chmod a+x notifyer.sh
    - ./notifyer.sh CD "$CI_JOB_STATUS" "$CI_COMMIT_AUTHOR" "$CI_COMMIT_BRANCH" "$CI_COMMIT_MESSAGE" "$CI_PIPELINE_ID" "$CI_JOB_STAGE"
  tags:
    - ajhin2
  allow_failure: false 
